export const GET_SOCIAL = "GET_SOCIAL";
export const CREATE_SOCIAL = "CREATE_SOCIAL";
export const UPDATE_SOCIAL = "UPDATE_SOCIAL";
export const DELETE_SOCIAL = "DELETE_SOCIAL";
export const SOCIAL_MESSAGE = "SOCIAL_MESSAGE";
